version: '3.8'
services:  

    postgresql:
        restart: always
        image: postgres:13
        container_name: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5434:5432" 
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - postgres       
	    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s


    mlflow:
        image: mlflow:1.0.0
        build: ./docker-mlflow
        container_name: mlflow_server
        ports:
            - "5000:5000"
        command: mlflow server -w 1 --backend-store-uri postgresql://postgres:postgres@postgresql/postgres --default-artifact-root /mlartifacts --host 0.0.0.0      
        volumes:
            - "./docker-mlflow/mlartifacts:/mlartifacts"
        networks:
            - postgres 
        depends_on:
            - postgresql



    airflow:
        image: airflow:1.0.0
        build: ./docker-airflow
        container_name: airflow
        ports:
            - '8088:8080'
        expose:
            - '8793'
        networks:
            - postgres
        environment:
            - TZ=Europe/Moscow
        volumes:
            - "/docker-airflow/dags:/airflow/dags" 
            - "/docker-mlflow/mlartifacts:/mlartifacts"
            - "/var/run/docker.sock:/var/run/docker.sock"
        command: 
            - /bin/bash
            - -c
            - |
              airflow db init
              airflow users create -r Admin -u admin -f admin -l admin -e admin@airflow.org -p admin
              airflow scheduler -D &
              airflow webserver -w 1 
        depends_on:
            - postgresql  
        
    db_init:
        image: db_init
        build: ./db-init
        container_name: db-init
        command: python3 main.py
        environment:
            - TABLE_DAY=value
        networks:
            - postgres 
        depends_on:
            - postgresql

networks:
  postgres:
    driver: bridge
volumes:
    postgres_data:  
    